### ISSUE TITLE
Release tasks

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-temp#79]
- [x] Move d3fc/d3fc out of the way
 - [x] Move ScottLogic/d3fc to d3fc/d3fc
 - [x] Move (old) d3fc to a legacy branch, and push (new) d3fc to master
 - [x] Update homepage url in package.json
 - [x] Update the url in CNAME / Custom Domain settings for the GitHub repo
 - [x] construct some release notes
 - [x] Enable semantic release
 - [x] update README.md
 - [x] Move d3fc/d3fc issues to new repo
 - [x] review old issues

**Comment by chrisprice** [comment]
Closing without doing the review of old issues
